#!/bin/bash

echo =====================================
echo "Thanks for installing this script
brought to you by TheHacker and @game_hacker080 ‬⁩

Just insert sourceutility or الخدمات in Terminal or OpenSSH and enjoy(:"
echo =====================================
