#!/bin/bash

echo =====================================
echo "Thanks for installing sourceutility v0.5"
echo ""
echo "Backups from <=0.3-1 will not work with 0.4"
echo =====================================
