#!/bin/bash

echo =====================================
echo sourceutility by TheHacker
echo "Run sourceutility in the Terminal to access the setup menu"
echo ""
echo "I HAD TO DISABLE RESTORING CYDIA SOURCES TEMPORARILY. I PROMISE I AM WORKING ON IT."
echo =====================================
