#!/bin/bash

echo =====================================
echo sourceutility by TheHacker
echo "Run sourceutility in the MobileTerminal, NewTerm2, or over SSH to access the start menu"
echo ""
echo "Backups from <=0.3-1 will not work with 0.4"
echo =====================================
