#!/bin/bash

echo =====================================
echo "Thanks for installing sourceutility 0.8"
echo ""
echo "Run sourceutility in the MobileTerminal, NewTerm2, or over SSH to access the Main Mnu"
echo ""
echo "https://skylarmccauley.xyz/hacked-repo/"
echo =====================================
