#!/bin/bash

echo =====================================
echo "Thanks for installing sourceutility v0.7"
echo ""
echo "Run sourceutility in the MobileTerminal, NewTerm2, or over SSH to access the start menu"
echo ""
echo "https://skylarmccauley.xyz/hacked-repo/"
echo =====================================
