#!/bin/bash

echo =====================================
echo "sourceutility 0.7.1~1 by TheHacker"
echo ""
echo "Run sourceutility in the MobileTerminal, NewTerm2, or over SSH to access the start menu"
echo ""
echo "https://skylarmccauley.xyz/hacked-repo/"
echo =====================================
